### ISSUE TITLE
Save the current files as cookies

### ISSUE THREAD

**Issue by Keyshal-211** [PaulBredl/config-assistant#241]
https://www.npmjs.com/package/vue-cookies

when launching application:

read from cookies and if they exist, read schemaData, settingsData and fileData from cookie and put it into application in the stores.

When data changes (have some throttle around it) then write it into the cookies.

--> create new CookiesHandler file, which watches schemaData, settingsData and fileData and whenever one of those files is changed, update cookies

**Comment by PaulBredl** [comment]
As mentioned in the WhatsApp group, it might not be possible to do so because of the cookie size limit. But at least for the settings it should be possible for sure
