### ISSUE TITLE
smart user help

### ISSUE THREAD

**Issue by PaulBredl** [PaulBredl/config-assistant#308]
add smart user help:

- for oneOf/anyOf, auto-select a sub-schema for which the current data is valid. And in code editor for properties, also use the "type" field to determine the suitable sub-schema (maybe not needed to be coded manually if already automatically done by schema validation)
- in schema editor: if user changes the sub schema of a property ( e.g. sets it to string property), then automatically update the "type" field to have the corresponding type

Other improvements:
- for new properties, use a different initial name, to make it clear that that is the name that users edit (they tend to think that the propertyName is just some label and on the right side of the table they can enter the name)
- in metaschema disallow new properties on root level

**Comment by PaulBredl** [comment]
We discussed that we  introduce a simplified meta schema for simple use cases which does not allow additional properties at root level
For the not-simplified schema: Would it might help if we rename the button somehow? I don't have an idea of a better name. Maybe we just give more introduction to JSON schema in the user studies

**Comment by Logende** [comment]
First PR that deals with the "automatically apply const after user selection": https://github.com/PaulBredl/config-assistant/pull/318

**Comment by Logende** [comment]
Second PR that auto infers oneOf selection: #320
