### ISSUE TITLE
Search can not find Property properly

### ISSUE THREAD

**Issue by PaulBredl** [PaulBredl/config-assistant#352]
if keyword is in description, it is shown that property also

**Comment by PaulBredl** [comment]
@Keyshal-211 we can discuss next meeting if we want to remove that

**Comment by Keyshal-211** [comment]
@PaulBredl should I do this? have you discussed in the meeting last time?

**Comment by PaulBredl** [comment]
No we haven't. I personally think it's fine as it is, but maybe @Logende and @beyond2void can share their opinion

**Comment by Logende** [comment]
I think it’s fine as it is
