### ISSUE TITLE
BUG: remove array item inside object seems buggy

### ISSUE THREAD

**Issue by PaulBredl** [PaulBredl/config-assistant#374]
Problem:
1. When inside an object, array item can't be removed.
2. Clicking on item index will create new array item.

**Comment by PaulBredl** [comment]
Could not be reproduced, possible fixed by removing the input next to the add item button

**Comment by PaulBredl** [comment]
@beyond2void did you manage to reproduce it?

**Comment by beyond2void** [comment]
> @beyond2void did you manage to reproduce it?

I tested, this issue doesn't exit any more.
I think we can close this issue.
